build:
  cuda_version: "12.1.1"
  python_packages:
    - torch==2.7.1
    - mistral_common==1.8.1
    - accelerate==1.9.0
    - librosa==0.11.0
    - hf-transfer==0.1.9
    - huggingface-hub==0.33.1
    - pydantic==2.11.7
    - inferless==0.2.15
    - transformers==4.54.1
